"""Train a model from a prepared long-form CSV.

Expected columns:
date, close, high, low, volume, plus the feature columns generated by app.features.technical.
This script intentionally does not fabricate data.
"""
import argparse
import pandas as pd
from app.features.technical import add_features, FEATURE_COLUMNS
from app.models.dataset import build_training_frame
from app.models.model import train_candidate, save_bundle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", default="models/active.joblib")
    args = parser.parse_args()

    df = pd.read_csv(args.input, parse_dates=["date"])
    df = add_features(df)
    frame, features = build_training_frame(df)
    split = int(len(frame) * 0.8)
    train, valid = frame.iloc[:split], frame.iloc[split:]
    bundle = train_candidate(train, valid, features)
    bundle.version = "model_v001"
    save_bundle(bundle, args.output)
    print(bundle.metrics)


if __name__ == "__main__":
    main()
